100 ejercicio en Numpy

Esta es una colección de ejercicios que se han recopilado en la lista de correo de numpy, en el desbordamiento de pila y en la documentación de numpy. El objetivo de esta colección es ofrecer una referencia rápida para usuarios nuevos y antiguos, pero también proporcionar una serie de ejercicios para quienes enseñan

1. Importe el paquete numpy con el nombre np (★☆☆)

In [1]:
import numpy as np

2. Imprima la versión numpy y la configuración (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.26.4
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.8",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas64",
      "found": true,
      "version": "0.3.23.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_

C:\Users\EQUIPO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


3. Crea un vector nulo de tamaño 10 (★☆☆)

In [27]:
vector = np.zeros(10, dtype=np.int32)
print(vector)

[0 0 0 0 0 0 0 0 0 0]


4. Cómo encontrar el tamaño de la memoria de cualquier matriz (★☆☆)

In [28]:
matriz = np.array([[1,2,4,5,6],[9,5,7,8,6]])
print(f'{matriz.size * matriz.itemsize} bytes') # itemsize --> Cantidad de bytes que almacena cada elemento de la matriz y size --> cantidad de elementos en la matriz

40 bytes


5. Crea un vector nulo(valor 0) de tamaño 10 pero el quinto valor es 1 (★☆☆)

In [29]:
vector = np.zeros(10, dtype=np.int64)
vector[4] = 1
print(vector)

[0 0 0 0 1 0 0 0 0 0]


6. Crea un vector con valores que van del 10 al 49 (★☆☆)

In [31]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


7. Invertir un vector (el primer elemento pasa a ser el último) (★☆☆)

In [42]:
vector = np.arange(0,20,2, dtype= np.int16)
print(f'Vector inicial: {vector}')
print('\n')
print(f'Vector inverso: {vector[::-1]}')

Vector inicial: [ 0  2  4  6  8 10 12 14 16 18]


Vector inverso: [18 16 14 12 10  8  6  4  2  0]


8. Crea una matriz de 3x3 con valores que van del 0 al 8 (★☆☆)

In [44]:
matriz_3_x_3 = np.linspace(0,8,9).reshape((3,3))
print(matriz_3_x_3)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


9. Encuentre índices de elementos distintos de cero de [1, 2, 0, 0, 4, 0] (★☆☆)

In [50]:
# Forma de encontrar mediante nonzero
vector = np.array([1, 2, 0, 0, 4, 0])
vector_filtro = vector.nonzero()
print(vector_filtro)

(array([0, 1, 4], dtype=int64),)


10. Create a 3x3 identity matrix (★☆☆)

In [61]:
# Se usara para creaer una matriz identity np.indentity(tanaño) dentro de la creación del array
matriz_indetity = np.array(np.identity(3), dtype=np.int16)
print(matriz_indetity)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


12. Crea una array de 3x3x3 con valores aleatorios (★☆☆)

In [241]:
# Usando random.random
matriz_aleatorio = np.random.random((3,3,3))
print(matriz_aleatorio)

[[[0.35190814 0.01082891 0.68729876]
  [0.69316537 0.83157829 0.50930232]
  [0.90464513 0.68407386 0.33956499]]

 [[0.4027021  0.96622912 0.30819911]
  [0.97108629 0.02915977 0.73643376]
  [0.66719608 0.47834223 0.11120668]]

 [[0.75105256 0.33119254 0.50002212]
  [0.39044083 0.29301264 0.37086485]
  [0.90464428 0.31676293 0.653326  ]]]


In [242]:
# Usando Random.randint
matriz_aleatorio = np.random.randint(0,100,size=(3,3,3))
print(matriz_aleatorio)

[[[45 57 97]
  [93 96  0]
  [13 92 81]]

 [[13 39 90]
  [37 82 38]
  [53 76 85]]

 [[55 95 81]
  [94  5 58]
  [17 58 39]]]


In [251]:
# Usando random.rand
matriz_aleatorio = np.random.rand(3,3,3)
print(matriz_aleatorio)

[[[0.79497388 0.68017276 0.03828644]
  [0.79299073 0.52095619 0.3568045 ]
  [0.71206012 0.7043754  0.66938595]]

 [[0.62992354 0.75463602 0.58443283]
  [0.68508614 0.9396663  0.65330543]
  [0.88648546 0.1326825  0.62625631]]

 [[0.78927026 0.52613174 0.04699351]
  [0.43961583 0.20434683 0.41417406]
  [0.09228599 0.5793665  0.65281871]]]
