100 ejercicio en Numpy

Esta es una colección de ejercicios que se han recopilado en la lista de correo de numpy, en el desbordamiento de pila y en la documentación de numpy. El objetivo de esta colección es ofrecer una referencia rápida para usuarios nuevos y antiguos, pero también proporcionar una serie de ejercicios para quienes enseñan

1. Importe el paquete numpy con el nombre np (★☆☆)

In [411]:
import numpy as np

2. Imprima la versión numpy y la configuración (★☆☆)

In [412]:
print(np.__version__)
np.show_config()

1.26.4
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.8",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas64",
      "found": true,
      "version": "0.3.23.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_

C:\Users\EQUIPO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


3. Crea un vector nulo de tamaño 10 (★☆☆)

In [413]:
vector = np.zeros(10, dtype=np.int32)
print(vector)

[0 0 0 0 0 0 0 0 0 0]


4. Cómo encontrar el tamaño de la memoria de cualquier matriz (★☆☆)

In [414]:
matriz = np.array([[1,2,4,5,6],[9,5,7,8,6]])
print(f'{matriz.size * matriz.itemsize} bytes') # itemsize --> Cantidad de bytes que almacena cada elemento de la matriz y size --> cantidad de elementos en la matriz

40 bytes


5. Crea un vector nulo(valor 0) de tamaño 10 pero el quinto valor es 1 (★☆☆)

In [415]:
vector = np.zeros(10, dtype=np.int64)
vector[4] = 1
print(vector)

[0 0 0 0 1 0 0 0 0 0]


6. Crea un vector con valores que van del 10 al 49 (★☆☆)

In [416]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


7. Invertir un vector (el primer elemento pasa a ser el último) (★☆☆)

In [417]:
vector = np.arange(0,20,2, dtype= np.int16)
print(f'Vector inicial: {vector}')
print('\n')
print(f'Vector inverso: {vector[::-1]}')

Vector inicial: [ 0  2  4  6  8 10 12 14 16 18]


Vector inverso: [18 16 14 12 10  8  6  4  2  0]


8. Crea una matriz de 3x3 con valores que van del 0 al 8 (★☆☆)

In [418]:
matriz_3_x_3 = np.linspace(0,8,9).reshape((3,3))
print(matriz_3_x_3)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


9. Encuentre índices de elementos distintos de cero de [1, 2, 0, 0, 4, 0] (★☆☆)

In [419]:
# Forma de encontrar mediante nonzero
vector = np.array([1, 2, 0, 0, 4, 0])
vector_filtro = vector.nonzero()
print(vector_filtro)

(array([0, 1, 4], dtype=int64),)


10. Create a 3x3 identity matrix (★☆☆)

In [420]:
# Se usara para creaer una matriz identity np.indentity(tanaño) dentro de la creación del array
matriz_indetity = np.array(np.identity(4), dtype=np.int16)
print(matriz_indetity)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


11. Crea una array de 3x3x3 con valores aleatorios (★☆☆)

In [421]:
# Usando random.random
matriz_aleatorio = np.random.random((3,3,3)) #valor de 0 a 1
print(matriz_aleatorio)

[[[0.24020618 0.13070497 0.94317807]
  [0.75286034 0.33340889 0.83635369]
  [0.71683551 0.25191154 0.9320081 ]]

 [[0.02215261 0.94282556 0.74442188]
  [0.24807644 0.69405259 0.56452978]
  [0.0575746  0.52505116 0.5338052 ]]

 [[0.94705862 0.97449632 0.66775995]
  [0.48701433 0.32967641 0.23892912]
  [0.19884594 0.42057958 0.50894522]]]


In [422]:
# Usando Random.randint
matriz_aleatorio = np.random.randint(0,101,size=(3,3,3))
print(matriz_aleatorio)

[[[ 91  34  84]
  [  4  40  60]
  [ 74 100  47]]

 [[100  25  48]
  [ 62  62  79]
  [ 41  21  91]]

 [[100  63  48]
  [ 26  69  90]
  [ 27  16  81]]]


In [423]:
# Usando random.rand
matriz_aleatorio = np.random.rand(3,3,3)
print(matriz_aleatorio)

[[[0.15570043 0.00617599 0.37498084]
  [0.14159691 0.53708501 0.54368539]
  [0.35334599 0.80739684 0.91031243]]

 [[0.2440864  0.61260067 0.34920316]
  [0.97542718 0.26415943 0.79929448]
  [0.01409721 0.04302952 0.47915915]]

 [[0.53022869 0.94820007 0.70304696]
  [0.12787286 0.43344751 0.81533061]
  [0.45833091 0.59397641 0.07141469]]]


12. Crea una matriz de 10x10 con valores aleatorios y encuentra los valores mínimo y máximo (★☆☆)

In [424]:
matriz_10_10 = np.random.randint(0,100, size=(10,10))
print(f'La matriz original es:\n{matriz_10_10}\n')
max_valor = matriz_10_10.max()
print(f'El valor maximo es: {max_valor}')
min_valor = matriz_10_10.min()
print(f'El valor mínimo es: {min_valor}')

La matriz original es:
[[ 8 31  1 99 62 79  9 23  3 38]
 [38 88 67 90 29 79 15  3 42 27]
 [ 5 27 33 10  5 86 36 40 19 95]
 [13 71 36 86 69 67 43 26 41 73]
 [48 97 15  3 51 12 10 81 72 19]
 [98  4 73 11 66 88 57 36 74 12]
 [77 89 35 70 89 31 34 51 97  1]
 [90  8 98 92 88 15 80 70 71 80]
 [92 41  8 54 70 46 33 29 96 98]
 [84 14 49 86 95 67  5 82 64 48]]

El valor maximo es: 99
El valor mínimo es: 1


13. Crea un vector aleatorio de tamaño 30 y encuentra el valor medio (★☆☆)

In [425]:
vector_30 = np.random.randint(0,200, size=30)
print(f'El vector original es:\n {vector_30}\n')
mean_vector_30 = vector_30.mean()
print(f'El Promedio del vector es: {mean_vector_30}')

El vector original es:
 [192  90 149  39 199 163  30  60  29  37 126 175 173 110 133 103  42 145
 149  95  38  57  80 123 155  33  18  14   9 172]

El Promedio del vector es: 97.93333333333334


14. Crea una matriz 2d con 1 en el borde y 0 dentro (★☆☆)

In [426]:
matriz_2d = np.ones((3,3), dtype=np.int32)
matriz_2d[1:-1,1:-1] = 0
matriz_2d

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

15. ¿Cómo agregar dos bordes (relleno con ceros) alrededor de una matriz existente? (★☆☆)

In [443]:
matriz_2d_ceros = np.random.randint(100, size=(8,8))
matriz_2d_ceros = np.pad(matriz_2d_ceros, pad_width=2, mode='constant', constant_values=1)
print(matriz_2d_ceros)

[[ 1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1 89 96 77 78 99 38 96 32  1  1]
 [ 1  1 15 30 11 64 79 98 27 35  1  1]
 [ 1  1 63 21 98  8 94 58 94 38  1  1]
 [ 1  1 43 70 11 76 12 63 23 49  1  1]
 [ 1  1 79  0 19  2 64 11 65 96  1  1]
 [ 1  1 91 40 38 67 32 96 35  3  1  1]
 [ 1  1 62 85 26 90 94 44 14 50  1  1]
 [ 1  1 48 61  1 45 72 98 87 54  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1]]


16. ¿Cuál es el resultado de la siguiente expresión? (★☆☆)

In [465]:
0 * np.nan  # NAN
np.nan == np.nan # False
np.inf > np.nan  # False
np.nan - np.nan  # False
np.nan in set([np.nan]) #
0.3 == 3 * 0.1 # False

False

17. Crea una matriz de 5x5 con valores 1,2,3,4 justo debajo de la diagonal (★☆☆)

In [599]:
matriz_5_5 = np.diag(1+np.arange(4),k=-1)
matriz_5_5

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

18. Crea una matriz de 8x8 y rellénala con un patrón de tablero de ajedrez (★☆☆)


In [608]:
matriz_8_8 = np.zeros((8,8),dtype=int)
matriz_8_8[1::2,::2] = 1
matriz_8_8[::2,1::2] = 1
print(matriz_8_8)

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


19. Considere una matriz de formas (6,7,8), ¿cuál es el índice (x,y,z) del elemento número 100? (★☆☆)

In [731]:
matriz_100 = np.random.randint(101,size =(6,7,8))
print(f'Matriz original :\n {matriz_100}\n')
#matriz_100[5,4,3] == 100
indice = np.argwhere(matriz_100 == 100)
print(f"Los índices de son: {indice}")


Matriz original :
 [[[ 96  19   9  69  58  49  39  96]
  [ 19  62  52  85  38  58   3  20]
  [  5  74  99  78  51  45  74  14]
  [ 93  14  74  98  57  13  78  15]
  [ 21   8  53  50  68  47  52  53]
  [ 81  19  92  94  69  58  63  81]
  [ 33  44  46   7  83  62  58  47]]

 [[ 36  71  64  63  59  75  26   4]
  [ 53  15  36  73  71  85  12 100]
  [ 37  39  49   6  90  10  91  40]
  [ 37  24  38  34   1  36  10  68]
  [ 77  50  44  28   0  99  75  65]
  [ 55  74   0  76  90   0  84  93]
  [ 14  11  73  64  82  30  72  22]]

 [[ 18  99  94 100  97  39  15  47]
  [ 63  82  49   5  13  59  68  27]
  [  5  28  76  14  21  35  14  54]
  [ 86  50 100  44  88  19   5   6]
  [ 71  44  39  45  98  36   8  15]
  [ 44  57  90  20  71  34  37  30]
  [ 71  86  23  47  28  64  25  92]]

 [[ 87  68  91  43  65  38   1  60]
  [ 84  24   8  97  96  29  73  37]
  [ 92  57  53  19  40   8  47   6]
  [ 10  79  73  50   5  17  50  93]
  [ 53  65  78  36  69  50  50  49]
  [ 10  37  61  15  11  63  62  43]
  [